### ISSUE TITLE
Slack Plugin

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/plugins#1]
Is there a corresponding docker-compose or kubernetes plugin for our slack container? https://github.com/madcore-ai/containers/tree/master/slack

Wiki with plugin usage (jenkins job) would also be helpful.

**Comment by botzill** [comment]
In fact there is no separate kubernetes files, specially for this plugin. I used the same principle as we have for madcore.deploy. If you check [bin/templates](https://github.com/madcore-ai/core/tree/master/bin/templates) you can find the kube service, controller that I'm using to deploy  the plugin.  I guess we need to define a proper way to do this. Do we need as well to define the kub files into the plugin repo?

**Comment by styk-tv** [comment]
Can you please define https://wiki.madcore.ai/plugins/slack and describe
steps to run. Without it its incomplete.

**Comment by botzill** [comment]
Add some docs: https://wiki.madcore.ai/plugins/slack
