### ISSUE TITLE
mailgun-flanker

### ISSUE THREAD

**Issue by styk-tv** [madcore-ai/plugins#118]
plugin name: mailgun-flanker
single account import only at this stage
picking up email from output folder of offlineimap plugin
importing into elasticsearch as json mimicking email/message structure including attachments

**Comment by styk-tv** [comment]
```
madcore plugin install: error: argument plugin_name: invalid choice: 'mailgun-flanker' (choose from 'elasticsearch', 'mailgunflanker', 'k8s', 'slack', 'ingress', 'flasker', 'spark', 'flasker-hub')
```
please do not forget to add dash between mailgun and flanker to:  mailgun-flanker

**Comment by phplaboratory** [comment]
Plugin based on mailgunflanker docker container with env variables:
ENV EMAILS_PATH /var/mailgunflanker
ENV ELASTICSEARCH "http://elasticserach:9200"
ENV ELASTICSEARCH_INDEX  "mailgunflanker"
